version: 0.2

batch:
  fast-fail: false
  build-fanout:
    parallelism: 3
    ignore-failure: false

phases:
  install:
    commands:
      - echo 'Installing Ruby dependencies'
      - apt-get update
      - apt-get install -y rbenv
      - rbenv install 3.2.2
      - gem install bundler -v 2.4.1
      - gem install cucumber
      - bundle install
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo 'Running Cucumber Tests'
      - cucumber
  post_build:
    commands:
      - echo "Would deploy here"
