version: 0.2

batch:
  fast-fail: true
  build-fanout:
    parallelism: 3
    ignore-failure: true

phases:
  install:
    commands:
      - echo 'Installing Ruby dependencies'
      - gem install bundler -v 2.4.1
      - bundle install
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo 'Running Cucumber Tests'
      - cucumber --init
      - codebuild-tests-run --test-command "cucumber" --files-search "codebuild-glob-search **/*.feature" 
      - cucumber
  post_build:
    commands:
      - echo "Would deploy here"
